#!/usr/bin/env sh
#basic_i3

intel-virtual-output
if xrandr -q | grep -i "virtual"; then
    if xrandr -q | grep -i " disconnected" ; then
        intel-virtual-output
    fi
    if xrandr -q | grep -i " connected" ; then
        xrandr --output VIRTUAL2 --off --output VIRTUAL1 --auto --pos 1900x0 --rotate normal --output eDP1 --primary --auto --pos 0x0 --rotate normal
        sleep 1
        xrandr --output VIRTUAL2 --off --output VIRTUAL1 --auto --pos 1920x0 --rotate normal --output eDP1 --primary --auto --pos 0x0 --rotate normal
    fi
fi
