#!/usr/bin/env sh

# brightness levels : 14000

current_brightness=$(cat /sys/class/backlight/intel_backlight/brightness)
max_brightness=$(cat /sys/class/backlight/intel_backlight/max_brightness)
new_brightness=$((current_brightness-2400))

[ $new_brightness -lt 0  ] && new_brightness=0
[ $new_brightness -gt $max_brightness  ] && new_brightness=$max_brightness

dir=$(dirname -- "$0")

if [ "$current_brightness" = "14000" ]; then
  lastBrightness=$(cat "$dir/brightnesslast")
  new_brightness="$lastBrightness"
else
  new_brightness="14000"
  echo "$current_brightness" | tee "$dir/brightnesslast" > /dev/null
fi

echo $new_brightness | sudo tee /sys/class/backlight/intel_backlight/brightness