#!/usr/bin/env sh

current_brightness=$(cat /sys/class/backlight/intel_backlight/brightness)
max_brightness=$(cat /sys/class/backlight/intel_backlight/max_brightness)

new_brightness=$((current_brightness+2400))

[ $new_brightness -gt $max_brightness  ] && new_brightness=$max_brightness

echo $new_brightness | sudo tee /sys/class/backlight/intel_backlight/brightness