#!/usr/bin/env sh
#brochgroup

dir=$(dirname -- "$0")

tabGroups=$(ls -1 "$dir/browserinfo/tabs" | sort)

tabList=""

tabList=$(echo "${tabGroups}" | dmenu -i -l 20 -p "select new tab group")
[ "$tabList" = "" ] && exit 0

broupdate

currentTabGroupName=$(cat "$dir/browserinfo/brocurrenttabgroup")
currentTabline=$(cat "$dir/browserinfo/brocurrenttabline")
currentTablineUrl=$(echo "$currentTabline" | grep -iPo "{\K.*?(?=}$)")

delLineNumber=$(grep -ion "$currentTablineUrl" "$dir/browserinfo/tabs/$currentTabGroupName" | grep -ioP "^\d+(?=:)")
if [ ! "$delLineNumber" = "" ]; then
  sed -i -e "${delLineNumber}d" "$dir/browserinfo/tabs/$currentTabGroupName"
fi

touch "$dir/browserinfo/tabs/$tabList"

echo "$currentTabline" >> "$dir/browserinfo/tabs/$tabList"
files=$(sort -u "$dir/browserinfo/tabs/$tabList" | grep -v "^{}$")
echo "$files" | tee "$dir/browserinfo/tabs/$tabList"
echo "$tabList" | tee "$dir/browserinfo/brocurrenttabgroup"




