#!/usr/bin/env sh
#broopen

query="$@"

if [ "$query" = "" ]; then
  echo "no query provided"
  exit 1 
fi

if echo "$query" | grep -iP "\w+\.\w+"; then
  if echo "$query" | grep -iP "^https?:"; then
    brourlopen "$query"
  else
    brourlopen "https://$query"
  fi
else  
  brourlopen "https://www.google.com/search?q=${query}"
fi

exit 0

