#!/usr/bin/env sh
#brotab

dir=$(dirname -- "$0")
sessionPath="/home/tausif/custombro/custombro/Sessions"

tabGroups=$(ls -1 "$dir/browserinfo/tabs" | sort)

tabList="$1"
query=""

if [ "$tabList" = "" ]; then
  tabList=$(echo "All\n${tabGroups}" | dmenu -i -l 20 -p "select tab group")
elif [ "$tabList" = "ctabg" ]; then
  tabList=$(cat "$dir/browserinfo/brocurrenttabgroup")
elif [ "$tabList" = "new" ]; then
  query=$(echo "" | dmenu -i -p "enter url or search")
fi

[ "$tabList" = "" ] && exit 0

queryF=""
if [ "$tabList" = "All" ]; then
  queryF=$(cat "$dir/browserinfo/tabs/*" | dmenu -i -l 20 -p "select tab" )
elif [ ! "$tabList" = "new" ]; then
  queryF=$(cat "$dir/browserinfo/tabs/$tabList" | dmenu -i -l 20 -p "select tab")
fi

[ ! "$tabList" = "new" ] && [ "$queryF" = "" ] && exit 0
[ "$tabList" = "new" ] && [ "$query" = "" ] && exit 0

currentTabLineX=$(DISPLAY=:0 xwininfo -tree -root | grep -v "has no name" | grep -v child | grep -i brave-browser | grep -i "\"brave-browser.*\"\ \"custom-bro\"")
currentOpenTabId=$(echo "$currentTabLineX" | grep -iPo "\b0x\w+")

if [ ! "$currentOpenTabId" = "" ]; then
  broupdate
  echo "" | tee "$dir/browserinfo/brocurrenttabgroup"
  echo "" | tee "$dir/browserinfo/brocurrenttabline"
  # close the existing tab
  DISPLAY=:0 wmctrl -ic "$currentOpenTabId"
  sleep 1
fi

rm -r "$sessionPath"
mkdir -p "$sessionPath"

exists="1"
if [ "$tabList" = "new" ]; then
  exists="0"
  tabList="_unsorted"
else 
  query=$(echo "$queryF" | grep -iPo "https?://.*?(?=}$)")
fi

echo "$tabList" | tee "$dir/browserinfo/brocurrenttabgroup"
# open new tab
broopen "$query"
sleep 3

currentTabLineX=$(DISPLAY=:0 xwininfo -tree -root | grep -v "has no name" | grep -v child | grep -i brave-browser | grep -v "\"brave-browser.*\"\ \"custom-bro\"")
currentOpenTabName=$(echo "$currentTabLineX" | grep -iPo "\b0x\w+\ \"\K.+?(?=\")")
sessionFileName=$(ls -1 "$sessionPath" | grep -i "^Session_")
currentTabUrl=$(chrome-session-dump "$sessionPath/$sessionFileName")
curNewTabLine=$(echo "${currentOpenTabName}{${currentTabUrl}}")

if [ "$exists" = "0" ]; then
  echo "$curNewTabLine" | tee "$dir/browserinfo/brocurrenttabline"
  fileLineCount=$(cat "$dir/browserinfo/tabs/$currentTabGroupName" | wc -l)
  if [ $fileLineCount -eq 0 ]; then
    echo "$curNewTabLine" > "$dir/browserinfo/tabs/$currentTabGroupName"
  else
    sed -i "1i ${curNewTabLine}\\" "$dir/browserinfo/tabs/$currentTabGroupName"
  fi
else
  echo "$queryF" | tee "$dir/browserinfo/brocurrenttabline"
fi
broupdate



