#!/usr/bin/env sh
#broupdate

dir=$(dirname -- "$0")
sessionPath="/home/tausif/custombro/custombro/Sessions"

currentTabLine=$(DISPLAY=:0 xwininfo -tree -root | grep -v "has no name" | grep -v child | grep -i brave-browser | grep -i "\"brave-browser.*\"\ \"custom-bro\"")
if [ "$currentTabLine" = "" ]; then
  echo "exiting..."
  exit 0
fi
echo "saving..."

currentOpenTabName=$(echo "$currentTabLine" | grep -iPo "\b0x\w+\ \"\K.+?(?=\")")
sessionFileName=$(ls -1 "$sessionPath" | grep -i "^Session_")
[ "$sessionFileName" = "" ] && exit 0
currentTabUrl=$(chrome-session-dump "$sessionPath/$sessionFileName" | head -n 1)
newTabLine=$(echo "${currentOpenTabName}{${currentTabUrl}}")

currentTabGroupName=$(cat "$dir/browserinfo/brocurrenttabgroup")
currentTabline=$(cat "$dir/browserinfo/brocurrenttabline")
currentTablineUrl=$(echo "$currentTabline" | grep -iPo "https?://.*?(?=}$)")

delLineNumber=$(grep -ion "$currentTablineUrl" "$dir/browserinfo/tabs/$currentTabGroupName" | grep -ioP "^\d+(?=:)")
fileLineCount=$(cat "$dir/browserinfo/tabs/$currentTabGroupName" | wc -l)

echo "$newTabLine" | tee "$dir/browserinfo/brocurrenttabline"
if [ ! "$delLineNumber" = "" ]; then
  sed -i "${delLineNumber}a ${newTabLine}\\" "$dir/browserinfo/tabs/$currentTabGroupName"
  sed -i -e "${delLineNumber}d" "$dir/browserinfo/tabs/$currentTabGroupName"
elif [ $fileLineCount -eq 0 ]; then
  echo "$newTabLine" > "$dir/browserinfo/tabs/$currentTabGroupName"
else
  sed -i "1i ${newTabLine}\\" "$dir/browserinfo/tabs/$currentTabGroupName"
fi

files=$(sort -u "$dir/browserinfo/tabs/$currentTabGroupName" | grep -v "^{}$")

echo "$files" | tee "$dir/browserinfo/tabs/$currentTabGroupName"

exit 0

