#!/usr/bin/env sh
#btconnect

if [ "$1" = "" ]; then
  echo "No device id given to connect"
  exit 1
fi

bluetoothctl connect "$1"

if [ "$?" = "0" ]; then
  dir=$(dirname -- "$0")
  echo "$1" > "$dir/btlasthex" 
fi