#!/usr/bin/env sh
#btrecon

dir=$(dirname -- "$0")
currentDevice=$(cat "$dir/btlasthex")

[ "$currentDevice" = "" ] && exit 1

count=$1
[ "$count" = "" ] && count=0
[ "$count" = "5" ] && echo "failed to reconnect" && exit 1
count=$((count+1))

echo "device: $currentDevice"
btdiscon
sleep 2
echo "trying to connect to : $currentDevice"
btconnect "$currentDevice" && echo "Successfully connected" && exit 0
echo "retrying for $currentDevice $count..."
btrecon $count 



 