#!/usr/bin/env sh

### THIS SCRIPT IS NOW DEPRECTED IN LIGHT OF NEW SYSTEM

#laptopscreenoff
displays=$(xrandr --current | grep -i connected | awk '{print $1}')
if echo $displays | grep -i HDMI -q  ; then
  input=$(echo $displays | awk '{print $1}')
  output=$(echo $displays | awk '{print $2}')
  xrandr --output $input --off --output $output --auto
fi
