#!/usr/bin/env sh

### THIS SCRIPT IS NOW DEPRECATED IS LIGHT OF NEW SYSTEM

#laptopscreenon
# xrandr --output eDP-1-1 --auto --output HDMI-1-1 --off
displays=$(xrandr --current | grep -i connected | awk '{print $1}')
if echo $displays | grep -i HDMI -q  ; then
  input=$(echo $displays | awk '{print $2}')
  output=$(echo $displays | awk '{print $1}')
  xrandr --output $input --off --output $output --auto
fi
