#!/usr/bin/env sh
#opsh
hostline=$(grep 'Host \w' ~/.ssh/config  | cut -c6- | dmenu -l 10 -p "choose server")
real_host=$(echo "$hostline" | awk '{printf "%s\n", $1 }')
[ "$real_host" = "" ] && exit 0
echo "$real_host"
x-terminal-emulator -e ssh $real_host
