#!/usr/bin/env sh

governor=$(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_available_governors | tr " " "\n" | dmenu)
echo $governor | sudo tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor
