#!/usr/bin/env sh
#sperf

governor=$(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_available_governors | tr " " "\n" | dmenu)
[ "$governor" = "" ] && exit 0
echo $governor | sudo tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor
