#!/usr/bin/env sh
#torurl

dir=$(dirname -- "$0")

selectedSite=$(ls "$dir/_torrentor/sites" | dmenu -p "select torrent site" -i -l 20)
newUrl=$(cat "$dir/_torrentor/sites/$selectedSite/urls" | grep -iv "^D:.*$" | dmenu -p "select default url" -l 20)
echo $newUrl
sed -i '$d' "$dir/_torrentor/sites/$selectedSite/urls"
echo "D:$newUrl" | tee -a "$dir/_torrentor/sites/$selectedSite/urls"

