#!/usr/bin/env sh

# playback_input=`pactl list sink-inputs short | awk '{print $1}' | head -1`
# pactl set-sink-input-mute $playback_input toggle
# pactl set-sink-mute 1 toggle

amixer sset "Master" toggle
