#!/usr/bin/env sh



videoUrl="$1"
outputFile=""
outputDir="/home/$USER/Downloads/music"
outputFile=""


createDirectory() {
  echo "created"
  mkdir -p "$outputDir"
}

if [ ! -d "$outputDir" ]; then
	createDirectory
fi

getUserInputs() {
  outputFile=$(echo "\n" | dmenu -i -p "Enter file name")
}

validateInputs() {
  [ "$videoUrl" = "" ] && exit 1
  [ "$outputFile" = "" ] && exit 1
}

getUserInputs
validateInputs

# we gonna do it hacky and get it done by  
finalUrl=$(node ./captureRequest.js "$videoUrl")
ffmpeg -i $finalUrl "$outputDir/$outputFile.mp3"
