#!/usr/bin/env sh



videoUrl="$1"
if [ "$videoUrl" = "" ]; then
  videoUrl=$(echo "" | dmenu -p "enter youtube link" -i)
fi
outputDir="/mnt/ssde/music"


createDirectory() {
  mkdir -p "$outputDir"
  echo "created"
}

if [ ! -d "$outputDir" ]; then
  outputDir="/home/$USER/Downloads/music"
  if [ ! -d "$outputDir" ]; then
    createDirectory
  fi
fi


[ "$videoUrl" = "" ] && exit 1
# we gonna do it hacky and get it done by  
youtube-dl "$videoUrl" -x
