#!/usr/bin/env sh
#bgswap

dir=$(dirname -- "$0")

light=$(cat "$dir/bgconfig" | grep -iPo "light=\K.*$")
dark=$(cat "$dir/bgconfig" | grep -iPo "dark=\K.*$")
current=$(cat "$dir/bgconfig" | grep -iPo "current=\K.*$")

if [ ! "$1" = "" ]; then
  if [ "$1" = "light" ]; then
    current="dark"
  else
    current="light"
  fi
fi

filepath=""
if [ "$current" = "light" ]; then
    filepath="$dark"
    sed -i "s/current=light/current=dark/" "$dir/bgconfig"
else
    filepath="$light"
    sed -i "s/current=dark/current=light/" "$dir/bgconfig"
fi


DISPLAY=:0 feh --bg-scale "$filepath"
DISPLAY=:8 feh --bg-scale "$filepath"